### ISSUE TITLE
Long Arabic texts are not showing properly

### ISSUE THREAD

**Issue by faisal95bd** [omaralalwi/Gpdf#10]
`<p>هذه جملة عربية طويلة تحتوي على العديد من الكلمات لتوضيح كيفية التعامل مع النصوص الطويلة في هذا السياق</p>`

- On the HTML it's showing fine
![image](https://github.com/user-attachments/assets/d8f64d76-2924-4490-a792-d213b4d239ec)

-  but on the PDF it's having issue, the first word shows on the next line.
![image](https://github.com/user-attachments/assets/e0c41ed3-0ceb-4864-9e04-b77a0760598c)

- I'm using `GpdfSet::MAX_CHARS_PER_LINE => 110,` in the config > gpdf.php file.

For long Arabic texts, the issue is happening. Another example below:
HTML output:
![image](https://github.com/user-attachments/assets/821aeddd-d104-4c10-ac54-d98124f7b22e)
PDF output:
![image](https://github.com/user-attachments/assets/a3654e86-bd3c-404d-9344-560789439832)

**Comment by faisal95bd** [comment]
> `<p>هذه جملة عربية طويلة تحتوي على العديد من الكلمات لتوضيح كيفية التعامل مع النصوص الطويلة في هذا السياق</p>`
> 
> * On the HTML it's showing fine
>   ![image](https://private-user-images.githubusercontent.com/33601113/384904420-d8f64d76-2924-4490-a792-d213b4d239ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjUzODQsIm5iZiI6MTczMTMyNTA4NCwicGF0aCI6Ii8zMzYwMTExMy8zODQ5MDQ0MjAtZDhmNjRkNzYtMjkyNC00NDkwLWE3OTItZDIxM2I0ZDIzOWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMzE2Y2M3ZWUyYWJkMjU4MGViY2Y0MzExMzVhMDJjNGI3YjJhZjQ2MGU2NDZiOTM0Mjc2MDlmMmY5ZjNjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2uF7Z1qYwf34TUbdCS93VQtOi_wyHY3eZAz_hF4expQ)
> * but on the PDF it's having issue, the first word shows on the next line.
>   ![image](https://private-user-images.githubusercontent.com/33601113/384904536-e0c41ed3-0ceb-4864-9e04-b77a0760598c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjUzODQsIm5iZiI6MTczMTMyNTA4NCwicGF0aCI6Ii8zMzYwMTExMy8zODQ5MDQ1MzYtZTBjNDFlZDMtMGNlYi00ODY0LTllMDQtYjc3YTA3NjA1OThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNmJmY2NhM2MxZTQ3NTUwZGQ5MWIwNmM0M2JlNWI2OGU4ZTYxODcyNWJkYmUxMDliMjk4Mjk0N2QxOTg1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HO-QChni256zexW2fEO6Kmf3Kt6Rb103bDzLh0vBh4o)
> * I'm using `GpdfSet::MAX_CHARS_PER_LINE => 110,` in the config > gpdf.php file.
> 
> For long Arabic texts, the issue is happening. Another example below: HTML output: ![image](https://private-user-images.githubusercontent.com/33601113/384905823-821aeddd-d104-4c10-ac54-d98124f7b22e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjUzODQsIm5iZiI6MTczMTMyNTA4NCwicGF0aCI6Ii8zMzYwMTExMy8zODQ5MDU4MjMtODIxYWVkZGQtZDEwNC00YzEwLWFjNTQtZDk4MTI0ZjdiMjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNzE5YmUzYWRhNTdiMzdjNjE1MDQ2ZmZlNDE0ZGYyYzJjOWE2OTQ0YTc3ZjcyZmI4NmY5NTBlYzRhMzhmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T4YRSHK0rbI5eV1pY-VyRuOlv20bLdTj2G7kCaGXxQE) PDF output: ![image](https://private-user-images.githubusercontent.com/33601113/384905330-a3654e86-bd3c-404d-9344-560789439832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjUzODQsIm5iZiI6MTczMTMyNTA4NCwicGF0aCI6Ii8zMzYwMTExMy8zODQ5MDUzMzAtYTM2NTRlODYtYmQzYy00MDRkLTkzNDQtNTYwNzg5NDM5ODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDExMzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOWEwZWZiOGYzYjc4MTkyNDEwN2Q3OGRkNmY4ODhkOTI5N2Y5Y2U1NmI4YmI2MjE1NDJkNTRiYjk0MmFkOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.braGLLFtub-Yr_GVonCHqwSz_W8lc6LFIFOC2sZazQ8)

@smahi for your kind information as well. Could you please assist too?

**Comment by faisal95bd** [comment]
@smahi for your kind information as well. Could you please assist too?

**Comment by omaralalwi** [comment]
please make sure to remove any custom css, if issue still , let me know

**Comment by omaralalwi** [comment]
resolved here https://github.com/omaralalwi/Gpdf/pull/9

please make sure to update latest version 1.0.6

then add this config key to config/gpdf.php file (if not already exists)
```
    GpdfSet::MAX_CHARS_PER_LINE => 100,
```
then clear config cache

it must fixed after these steps .

![2024-11-11_22-49](https://github.com/user-attachments/assets/a81e13e6-1ffd-493d-882e-39f894ec5f09)

**Comment by faisal95bd** [comment]
**Thanks for the feedback! Still facing the issue though.**
- I removed & reinstalled the package, cleared the config cache; but the issue persists.
- Cloned the [Demo Laravel App](https://github.com/omaralalwi/Gpdf-Laravel-Demo) and checked from it too, the issue persists.
- Demo [HTML code](https://codeshare.io/g8DrkY)

![image](https://github.com/user-attachments/assets/4b5065b3-e5f4-4579-ab2d-c553ebf36bc8)

- **HTML output**

![image](https://github.com/user-attachments/assets/cbc8ddf5-9773-4499-8f11-cf3424de9a04)

- **PDF output**

![image](https://github.com/user-attachments/assets/def97775-0085-4b16-87fc-788443906489)

- config > gpdf.php

![image](https://github.com/user-attachments/assets/d3f59380-1bf5-4f7d-ab6a-5971fe7894c6)

**Comment by faisal95bd** [comment]
Hi @omaralalwi, @smahi just wanted to follow up on this issue. Any updates on the fix? Let me know if you need any further information or assistance from my side. Appreciate your help! 
Thanks!

**Comment by omaralalwi** [comment]
the long arabic texts (in many lines) have some issues with domPDF so , you resolve issue easly by divide too long strings to make paragraphs
second scenario (related to table) you can add cutom styles to table tr and td (like example with generateAdvanceWithFixedHeader in demo app)
